-- Market Intelligence Aggregator - Database Schema
-- Run this script in Supabase SQL Editor or via psql
-- 
-- Prerequisites:
-- 1. Create a Supabase project at https://supabase.com
-- 2. Enable the following extensions in the Supabase Dashboard:
--    - vector (for pgvector embeddings)
--    - timescaledb (for time-series optimization)

-- =============================================================================
-- EXTENSIONS
-- =============================================================================
-- Note: In Supabase, you may need to enable these via the Dashboard first
CREATE EXTENSION IF NOT EXISTS vector;
-- TimescaleDB may need to be enabled via Supabase dashboard
-- CREATE EXTENSION IF NOT EXISTS timescaledb;

-- =============================================================================
-- PORTFOLIO HOLDINGS
-- =============================================================================
-- Stores current Robinhood portfolio positions
-- Updated daily by the Python portfolio fetcher
DROP TABLE IF EXISTS holdings CASCADE;
CREATE TABLE holdings (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    quantity DECIMAL(18, 8) NOT NULL,
    avg_cost DECIMAL(18, 4) NOT NULL,
    current_price DECIMAL(18, 4),
    market_value DECIMAL(18, 4),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_holdings_ticker ON holdings (ticker);
CREATE INDEX idx_holdings_updated ON holdings (updated_at DESC);

-- =============================================================================
-- MARKET DATA
-- =============================================================================
-- Stores historical OHLCV data from Alpha Vantage
-- Converted to hypertable for time-series optimization
DROP TABLE IF EXISTS market_data CASCADE;
CREATE TABLE market_data (
    id SERIAL,
    ticker VARCHAR(10) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    open DECIMAL(18, 4),
    high DECIMAL(18, 4),
    low DECIMAL(18, 4),
    close DECIMAL(18, 4),
    volume BIGINT,
    vwap DECIMAL(18, 4),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id, timestamp)
);

-- Convert to hypertable if TimescaleDB is available
-- Uncomment if TimescaleDB extension is enabled
-- SELECT create_hypertable('market_data', 'timestamp', if_not_exists => TRUE);

CREATE INDEX idx_market_data_ticker_timestamp ON market_data (ticker, timestamp DESC);
CREATE INDEX idx_market_data_ticker ON market_data (ticker);

-- =============================================================================
-- TECHNICAL INDICATORS
-- =============================================================================
-- Stores calculated technical indicators (RSI, SMA, MACD, etc.)
-- Calculated by Python pandas-ta service
DROP TABLE IF EXISTS technical_indicators CASCADE;
CREATE TABLE technical_indicators (
    id SERIAL,
    ticker VARCHAR(10) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    rsi_14 DECIMAL(10, 4),
    sma_50 DECIMAL(18, 4),
    sma_200 DECIMAL(18, 4),
    macd DECIMAL(18, 4),
    macd_signal DECIMAL(18, 4),
    atr_14 DECIMAL(18, 4),
    volume_avg_20 BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id, timestamp)
);

-- Convert to hypertable if TimescaleDB is available
-- Uncomment if TimescaleDB extension is enabled
-- SELECT create_hypertable('technical_indicators', 'timestamp', if_not_exists => TRUE);

CREATE INDEX idx_tech_ticker_timestamp ON technical_indicators (ticker, timestamp DESC);
CREATE INDEX idx_tech_ticker ON technical_indicators (ticker);

-- =============================================================================
-- CREATOR CONTENT
-- =============================================================================
-- Stores tweets/content from tracked creators with embeddings for semantic search
-- Embeddings generated by Python sentence-transformers (384 dimensions)
DROP TABLE IF EXISTS creator_content CASCADE;
CREATE TABLE creator_content (
    id SERIAL PRIMARY KEY,
    creator_name VARCHAR(100) NOT NULL,
    platform VARCHAR(50) DEFAULT 'twitter',
    content_id VARCHAR(100) UNIQUE NOT NULL,
    content_text TEXT NOT NULL,
    mentioned_tickers TEXT[], -- Array of tickers mentioned in content
    sentiment VARCHAR(20), -- bullish, bearish, neutral
    confidence_score DECIMAL(5, 4), -- 0.0000 to 1.0000
    embedding vector(384), -- sentence-transformers all-MiniLM-L6-v2 dimension
    posted_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_creator_posted_at ON creator_content (posted_at DESC);
CREATE INDEX idx_creator_name ON creator_content (creator_name);
CREATE INDEX idx_creator_sentiment ON creator_content (sentiment);
-- IVFFlat index for approximate nearest neighbor search
-- Note: Need at least 100 rows before this index works well
CREATE INDEX idx_creator_embedding ON creator_content USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- =============================================================================
-- SIGNALS (Historical Recommendations)
-- =============================================================================
-- Stores generated buy/hold/wait signals for backtesting and analysis
DROP TABLE IF EXISTS signals CASCADE;
CREATE TABLE signals (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    signal_type VARCHAR(20) NOT NULL, -- buy, hold, wait
    recommendation_amount DECIMAL(18, 4),
    confidence_score DECIMAL(5, 4),
    reasoning TEXT,
    market_regime VARCHAR(50), -- calm, volatile, bearish, bullish
    vix_level DECIMAL(10, 4),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_signals_ticker_created ON signals (ticker, created_at DESC);
CREATE INDEX idx_signals_created ON signals (created_at DESC);
CREATE INDEX idx_signals_type ON signals (signal_type);

-- =============================================================================
-- CREATOR ACCURACY TRACKING
-- =============================================================================
-- Tracks historical accuracy of creator predictions for weighting
DROP TABLE IF EXISTS creator_accuracy CASCADE;
CREATE TABLE creator_accuracy (
    id SERIAL PRIMARY KEY,
    creator_name VARCHAR(100) NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    prediction_date DATE NOT NULL,
    predicted_sentiment VARCHAR(20),
    actual_price_change DECIMAL(10, 4), -- % change over next 7 days
    was_accurate BOOLEAN,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_creator_accuracy ON creator_accuracy (creator_name, was_accurate);
CREATE INDEX idx_accuracy_date ON creator_accuracy (prediction_date DESC);

-- =============================================================================
-- CONFIGURATION
-- =============================================================================
-- Stores system configuration as JSONB for flexibility
DROP TABLE IF EXISTS config CASCADE;
CREATE TABLE config (
    key VARCHAR(100) PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default configuration values
INSERT INTO config (key, value) VALUES
    ('tracked_tickers', '["SPY", "QQQ", "VOO", "VTI"]'),
    ('creators', '[
        {"name": "Moby Invest", "twitter_handle": "mobyinvest"},
        {"name": "Carbon Finance", "twitter_handle": "carbonfinance"}
    ]'),
    ('confidence_weights', '{
        "creator_consensus": 0.3,
        "technical_alignment": 0.3,
        "volume_confirmation": 0.2,
        "historical_accuracy": 0.2
    }'),
    ('market_regime_thresholds', '{
        "vix_high": 25,
        "rsi_overbought": 70,
        "rsi_oversold": 30
    }'),
    ('contribution_target', '{
        "monthly": 1000,
        "annual": 7000,
        "current": 600
    }')
ON CONFLICT (key) DO UPDATE SET 
    value = EXCLUDED.value,
    updated_at = NOW();

-- =============================================================================
-- HELPER FUNCTIONS
-- =============================================================================

-- Function to get similar content based on embedding similarity
CREATE OR REPLACE FUNCTION search_similar_content(
    query_embedding vector(384),
    match_threshold FLOAT DEFAULT 0.7,
    match_count INT DEFAULT 5
)
RETURNS TABLE (
    id INT,
    creator_name VARCHAR(100),
    content_text TEXT,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        cc.id,
        cc.creator_name,
        cc.content_text,
        1 - (cc.embedding <=> query_embedding) AS similarity
    FROM creator_content cc
    WHERE cc.embedding IS NOT NULL
        AND 1 - (cc.embedding <=> query_embedding) > match_threshold
    ORDER BY cc.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- Function to get latest market data for a ticker
CREATE OR REPLACE FUNCTION get_latest_market_data(p_ticker VARCHAR(10))
RETURNS TABLE (
    out_ticker VARCHAR(10),
    out_timestamp TIMESTAMPTZ,
    out_open DECIMAL(18, 4),
    out_high DECIMAL(18, 4),
    out_low DECIMAL(18, 4),
    out_close DECIMAL(18, 4),
    out_volume BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        md.ticker,
        md.timestamp,
        md.open,
        md.high,
        md.low,
        md.close,
        md.volume
    FROM market_data md
    WHERE md.ticker = p_ticker
    ORDER BY md.timestamp DESC
    LIMIT 1;
END;
$$;

-- Function to get creator accuracy rate
CREATE OR REPLACE FUNCTION get_creator_accuracy_rate(p_creator_name VARCHAR(100))
RETURNS DECIMAL(5, 4)
LANGUAGE plpgsql
AS $$
DECLARE
    accuracy_rate DECIMAL(5, 4);
BEGIN
    SELECT COALESCE(AVG(CASE WHEN was_accurate THEN 1.0 ELSE 0.0 END), 0.5)
    INTO accuracy_rate
    FROM creator_accuracy
    WHERE creator_name = p_creator_name
        AND prediction_date >= CURRENT_DATE - INTERVAL '90 days';
    
    RETURN accuracy_rate;
END;
$$;

-- =============================================================================
-- ROW LEVEL SECURITY (Optional - for multi-user scenarios)
-- =============================================================================
-- For personal use, RLS is disabled. Enable if sharing database.
-- ALTER TABLE holdings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE market_data ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE technical_indicators ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE creator_content ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE creator_accuracy ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- GRANTS (Supabase handles this automatically for authenticated users)
-- =============================================================================
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authenticated;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- =============================================================================
-- VERIFICATION
-- =============================================================================
-- Run these queries to verify setup:
-- SELECT * FROM config;
-- SELECT COUNT(*) FROM holdings;
-- \d+ market_data
-- \d+ creator_content
